language: python

virtualenv:
    system_site_packages: true

python:
    - "2.7"

before_install:
    - sudo apt-get update -qq -y
    - sudo pip install git+https://github.com/azvoleff/pyabm.git#egg=pyabm
    - sudo apt-get install -qq python-numpy python-matplotlib python-dev cython libhdf5-dev
      # numexpr>=2.0.0 is needed due to for tables>=2.4.0 (cython>=.13 is also 
      # needed for tables)
    - sudo pip install -q "numexpr>=2.0.0"

install:
    - pip install .

script: nosetests

notifications:
  email:
    on_success: change
    on_failure: change
